# Generated by Django 5.2 on 2025-08-20 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название продукта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('weight', models.CharField(blank=True, max_length=50, verbose_name='Вес/Объем')),
                ('shelf_life', models.CharField(blank=True, max_length=100, verbose_name='Срок годности')),
                ('proteins', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Белки')),
                ('fats', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Жиры')),
                ('carbohydrates', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Углеводы')),
                ('calories', models.IntegerField(blank=True, null=True, verbose_name='Калорийность')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
    ]
