# Generated by Django 5.2 on 2025-08-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.TextField(default='Не указан', verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Собирается'), ('in_transit', 'В пути'), ('delivered', 'На почте')], default='pending', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
