# Generated by Django 5.2 on 2025-08-20 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order_address_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка категории'),
        ),
    ]
