# Generated by Django 5.2.3 on 2025-08-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to='category_icons/', verbose_name='Иконка категории'),
        ),
    ]
