# Generated by Django 5.2.3 on 2025-08-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_category_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст отзыва'),
        ),
    ]
